version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pg_data:
